export enum ACCOMMODATION_CLASS {
  HARD_COMPARTMENT_CLASS = 'HardCompartmentClass',
  SOFT_COMPARTMENT_CLASS = 'SoftCompartmentClass',
  MIXED_SOFT_CLASS = 'MixedSoftClass',
  MIXED_HARD_CLASS = 'MixedHardClass',
  HIGH_GRADE_SOFT_CLASS = 'HighGradeSoftClass',
  SPECIAL_CLASS = 'SpecialClass',
  HARD_CLASS = 'HardClass',
  SOFT_CLASS = 'SoftClass',
  GRAN_CLASSE = 'GranClasse',
  DELUXE = 'Deluxe',
  COACH = 'Coach',
  LEISURE = 'Leisure',
  BUSINESS = 'Business',
  PREMIUM = 'Premium',
  SECOND_CLASS = 'SecondClass',
  FIRST_CLASS = 'FirstClass',
  OTHER = 'Other_',
}
