export enum DOCUMENT_TYPE {
  NATURALIZATION_CERTIFICATE = 'NaturalizationCertificate',
	PASSPORT_CARD = 'PassportCard',
	CREW_MEMBER_CERTIFICATE = 'CrewMemberCertificate',
	AIR_NEXUS_CARD = 'AirNexusCard',
	MERCHANT_MARINER = 'MerchantMariner',
	NON_STANDARD = 'Non-standard',
	KNOWN_TRAVELER_NUMBER = 'KnownTravelerNumber',
	REDRESS_NUMBER = 'RedressNumber',
	PERMANENT_RESIDENT_CARD = 'PermanentResidentCard',
	PILOTS_LICENSE = 'PilotsLicense',
	REFUGEE_TRAVEL_DOCUMENT = 'RefugeeTravelDocument',
	BORDER_CROSSING_CARD = 'BorderCrossingCard',
	VERHICLE_REGISTRATION_NUMBER = 'VerhicleRegistrationNumber',
	TAXEX_EMPTION_NUMBER = 'TaxexEmptionNumber',
	INSURANCE_POLICY_NUMBER = 'InsurancePolicyNumber',
	ALIEN_REGISTRATION_NUMBER = 'AlienRegistrationNumber',
	VACCINATION_CERTIFICATE = 'VaccinationCertificate',
	NATIONAL_IDENTITY_DOCUMENT = 'NationalIdentityDocument',
	DRIVERS_LICENSE = 'DriversLicense',
	MILITARY_IDENTIFICATION = 'MilitaryIdentification',
	PASSPORT = 'Passport',
	VISA = 'Visa',
	OTHER = 'Other_'
}