export enum INFORMATION_TYPE {
  ADDRESS = 'Address',
	ADVISORY = 'Advisory',
	ALIAS_NAME = 'Alias name',
	AMENITIES = 'Amenities',
	ATTRACTIONS = 'Attractions',
	AWARDS = 'Awards',
	CONTACT = 'Contact',
	CORPORATE_LOCATIONS = 'Corporate locations',
	DESCRIPTION = 'Description',
	DESCRIPTIVE_CONTENT = 'Descriptive content',
	DINING = 'Dining',
	DRIVING_DIRECTIONS = 'Driving directions',
	FACILITIES = 'Facilities',
	GEOCODES = 'Geocodes',
	LOCATION = 'Location',
	LONG_NAME = 'Long name',
	MARKETING = 'Marketing',
	PICTURES = 'Pictures',
	POLICY = 'Policy',
	RECREATION = 'Recreation',
	SAFETY = 'Safety',
	SERVICES = 'Services',
	SHORT_DESCRIPTION = 'Short description',
	SPECIAL_INSTRUCTIONS = 'Special instructions',
	TRANSPORTATION = 'Transportation',
	OTHER = 'Other_'
}