export enum INVENTORY_BLOCK_TYPE {
  AIRLINE_CREW = 'AirlineCrew',
	COMPLIMENTARY = 'Complimentary',
	CONTRACT = 'Contract',
	CORPORATE_GROUP = 'Corporate group',
	CORPORATE_LEASE = 'Corporate lease',
	EDUCATION = 'Education',
	FRATERNITY = 'Fraternity',
	GOVERNMENT_MILITARY = 'Government/military',
	INSURANCE = 'Insurance',
	INTERNATIONAL_ASSOCIATION = 'International association',
	MARINA = 'Marina',
	NATIONAL_ASSOCIATION = 'National association',
	NEGOTIATED_SPECIAL_CORPORATE = 'Negotiated/special corporate',
	OTHER = 'Other',
	PERMANENT_LEASE = 'Permanent lease',
	REGIONAL_STATE_LOCAL_ASSOCIATION = 'Regional/state/local association',
	RELIGIOUS = 'Religious',
	SOCIAL = 'Social',
	SPORTS = 'Sports',
	TOUR_AND_TRAVEL = 'Tour and travel',
	WHOLESALER = 'Wholesaler',
	OTHER = 'Other_'
}