export enum LOCATION_CATEGORY {
  AIRPORT = 'Airport',
	BAY = 'Bay',
	BEACH = 'Beach',
	BEACHFRONT = 'Beachfront',
	BUISNESS_DISTRICT = 'Buisness district',
	CITY = 'City',
	DOWNTOWN = 'Downtown',
	ENTERTAINMENT_DISTRICT = 'Entertainment district',
	EXPRESSWAY = 'Expressway',
	FINANCIAL_DISTRICT = 'Financial district',
	GULF = 'Gulf',
	LAKE = 'Lake',
	MARINA = 'Marina',
	MOUNTAIN = 'Mountain',
	OCEANFRONT = 'Oceanfront',
	PARK = 'Park',
	RESORT = 'Resort',
	RIVER = 'River',
	RURAL = 'Rural',
	SHOPPING_DISTRICT = 'Shopping district',
	SUBURBAN = 'Suburban',
	THEATRE_DISTRICT = 'Theatre district',
	WATERFRONT = 'Waterfront',
	OTHER = 'Other_'
}