export enum MEAL_TYPE {
  RGML = 'RGML',
	VLML = 'VLML',
	VGML = 'VGML',
	SPML = 'SPML',
	SFML = 'SFML',
	RVML = 'RVML',
	PRML = 'PRML',
	ORML = 'ORML',
	NLML = 'NLML',
	MOML = 'MOML',
	LSML = 'LSML',
	LPML = 'LPML',
	LFML = 'LFML',
	LCML = 'LCML',
	KSML = 'KSML',
	HNML = 'HNML',
	HFML = 'HFML',
	GFML = 'GFML',
	FPML = 'FPML',
	DBML = 'DBML',
	CHML = 'CHML',
	BLML = 'BLML',
	BBML = 'BBML',
	AVML = 'AVML',
	OTHER = 'Other_'
}