export enum MEAL_PLAN {
  BREAKFAST_LUNCH = 'Breakfast & lunch',
	DINNER = 'Dinner',
	LUNCH = 'Lunch',
	MODIFIED = 'Modified',
	BREAKFAST = 'Breakfast',
	FAMILY_AMERICAN = 'Family American',
	DINNER_BED_AND_BREAKFAST_PLAN = 'Dinner bed and breakfast plan',
	BERMUDA = 'Bermuda',
	SELF_CATERING = 'Self catering',
	ROOM_ONLY_EUROPEAN_PLAN = 'Room only/European plan',
	AS_BROCHURED = 'As brochured',
	HALF_BOARD_MODIFIED_AMERICAN_PLAN = 'Half board/modified American plan',
	FULL_BREAKFAST = 'Full breakfast',
	FULL_BOARD = 'Full board',
	FAMILY_PLAN = 'Family plan',
	EUROPEAN_PLAN = 'European plan',
	ENGLISH_BREAKFAST = 'English breakfast',
	CONTINENTAL_BREAKFAST = 'Continental breakfast',
	CARIBBEAN_BREAKFAST = 'Caribbean breakfast',
	BUFFET_BREAKFAST = 'Buffet breakfast',
	BED_BREAKFAST = 'Bed & breakfast',
	AMERICAN_FULL_BOARD = 'American/full board',
	ALL_INCLUSIVE = 'All inclusive',
	OTHER = 'Other_'
}