export enum PAYMENT_CARD_ISSUER {
  VISA = 'VISA',
	US_AIRWAYS = 'USAirways',
	UNITED_AIRLINES = 'UnitedAirlines',
	STARWOOD_HOTELS = 'StarwoodHotels',
	SOUTHWEST_AIRLINES = 'SouthwestAirlines',
	RITZ_CARLTON = 'RitzCarlton',
	MASTERCARD = 'Mastercard',
	MARIOTT = 'Mariott',
	HYATT = 'Hyatt',
	HILTON = 'Hilton',
	EUROCARD = 'Eurocard',
	DISNEY = 'Disney',
	DISCOVER_CARD = 'DiscoverCard',
	DELTA_AIRLINES = 'DeltaAirlines',
	CONTINENTAL_AIRLINES = 'ContinentalAirlines',
	CITIBANK = 'Citibank',
	CHASE = 'Chase',
	CAPITAL_ONE = 'CapitalOne',
	BRITISH_AIRWAYS = 'BritishAirways',
	BANK_OF_AMERICA = 'BankOfAmerica',
	AMERICAN_EXPRESS = 'AmericanExpress',
	OTHER = 'Other_'
}