export enum PICTURE_CATEGORY {
  BALLROOM = 'Ballroom',
	BAR_LOUNGE = 'Bar/Lounge',
	BASICS = 'Basics',
	BEACH = 'Beach',
	BUSINESS_CENTER = 'Business center',
	EXTERIOR_VIEW = 'Exterior view',
	GOLF_COURSE = 'Golf course',
	GUEST_ROOM = 'Guest room',
	GUEST_ROOM_AMENITY = 'Guest room amenity',
	HEALTH_CLUB = 'Health club',
	HOT_NEWS = 'Hot news',
	LOBBY_VIEW = 'Lobby view',
	LOGO = 'Logo',
	MAP = 'Map',
	MEETING_ROOM = 'Meeting room',
	MISCELLANEOUS = 'Miscellaneous',
	POOL_VIEW = 'Pool view',
	PROMOTIONAL = 'Promotional',
	PROPERTY_AMENITY = 'Property amenity',
	RECREATIONAL_FACILITY = 'Recreational facility',
	RESTAURANT = 'Restaurant',
	SPA = 'Spa',
	SUITE = 'Suite',
	OTHER = 'Other_'
}