export enum PROFILE_TYPE {
  AIRLINE = 'Airline',
	ARRANGER = 'Arranger',
	ASSOCIATION = 'Association',
	AUTHORIZED_SIGNER = 'Authorized signer',
	BILLING_CONTACT = 'Billing contact',
	CAR_RENTAL = 'Car rental',
	CORPORATION = 'Corporation',
	CRO = 'CRO',
	CRUISE_LINE = 'Cruise line',
	CUSTOMER = 'Customer',
	EMPLOYEE = 'Employee',
	EVENT_HOST = 'Event host',
	GDS = 'GDS',
	GENERAL_SERVICE_CONTRACTOR = 'General service contractor',
	GROUP = 'Group',
	HOTEL = 'Hotel',
	INTERNET_BROKER = 'Internet broker',
	REPRESENTATION_COMPANY = 'Representation company',
	SUPPLIER_PARTNER = 'Supplier partner',
	TOUR_OPERATOR = 'Tour operator',
	TRAVEL_AGENCY = 'Travel agency',
	TRAVEL_AGENT = 'Travel agent',
	WHOLESALER = 'Wholesaler',
	OTHER = 'Other_'
}