export enum RESTAURANT_BAR_CATEGORY {
  BEVERAGE = 'Beverage',
	BUFFET = 'Buffet',
	CAFE = 'Cafe',
	CAFETERIA = 'Cafeteria',
	CASUAL = 'Casual',
	FAMILY = 'Family',
	FAST_FOOD = 'Fast food',
	FINE_DINING = 'Fine dining',
	KIOSK = 'Kiosk',
	TAKE_OUT = 'Take out',
	BAR_LOUNGE = 'Bar/lounge',
	BRASSERIE = 'Brasserie',
	COFFEE_BAR = 'Coffee bar',
	SNACK_BAR = 'Snack bar',
	FULL_SERVICE = 'Full service',
	PUB = 'Pub',
	DELI = 'Deli',
	PRIVATE_DINING = 'Private dining',
	SPORTS_BAR = 'Sports bar',
	PIANO_BAR = 'Piano bar',
	OUTDOOR_BAR_CAFE = 'Outdoor bar/cafe',
	BEER_GARDEN = 'Beer garden',
	BEACH_BAR = 'Beach bar',
	TAPAS_BAR = 'Tapas bar',
	OTHER = 'Other_'
}