export enum TAX_TYPE {
  ASSESSMENT_LICENSE_TAX = 'Assessment/license tax',
	BED_TAX = 'Bed tax',
	CITY_TAX = 'City tax',
	CONVENTION_TAX = 'Convention tax',
	COUNTRY_TAX = 'Country tax',
	COUNTY_TAX = 'County tax',
	ENERGY_TAX = 'Energy tax',
	FEDERAL_TAX = 'Federal tax',
	FOOD_BEVERAGE_TAX = 'Food & beverage tax',
	GOODS_AND_SERVICES_TAX_GST = 'Goods and services tax (GST)',
	INSURANCE_PREMIUM_TAX = 'Insurance Premium Tax',
	LODGING_TAX = 'Lodging tax',
	NATIONAL_GOVERNMENT_TAX = 'National government tax',
	OCCUPANCY_TAX = 'Occupancy tax',
	ROOM_TAX = 'Room Tax',
	SALES_TAX = 'Sales tax',
	STATE_TAX = 'State tax',
	SURPLUS_LINES_TAX = 'Surplus Lines Tax',
	TOTAL_TAX = 'Total tax',
	TOURISM_TAX = 'Tourism tax',
	VALUE_ADDED_TAX_VAT = 'Value Added Tax (VAT)',
	OTHER = 'Other_'
}