export const COMMON_ERRORS = {
  MUST_BE_A_STRING: "MUST_BE_A_STRING",
  MUST_BE_LESS_THAN_X_CHARACTERS: (x: number) => `MUST_BE_LESS_THAN_${x}_CHARACTERS`,
  MUST_BE_MORE_THAN_X_CHARACTERS: (x: number) => `MUST_BE_MORE_THAN_${x}_CHARACTERS`
}