export const USER_ERRORS = {
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORD_INVALID: "PASSWORD_INVALID",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_INVALID: "EMAIL_INVALID",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  MUST_BE_LESS_THAN_X_CHARACTERS: (x: number) => `MUST_BE_LESS_THAN_${x}_CHARACTERS`,
  MUST_BE_MORE_THAN_X_CHARACTERS: (x: number) => `MUST_BE_MORE_THAN_${x}_CHARACTERS`
}