export enum BedTypes {
  BUNK_BED = 'BUNK_BED',
  FULL_BED = 'FULL_BED',
  FUTON = 'FUTON',
  KING_BED = 'KING_BED',
  MURPHY_BED = 'MURPHY_BED',
  QUEEN_BED = 'QUEEN_BED',
  SOFA_BED = 'SOFA_BED',
  TRUNDLE_BED = 'TRUNDLE_BED',
  TWIN_BED = 'TWIN_BED',
  TWIN_XL_BED = 'TWIN_XL_BED',
  WATER_BED = 'WATER_BED',
}
