export enum PerStayFees {
  None = 'None',
  '1stNightRoomAndTax' = '1stNightRoomAndTax',
  '2NightsRoomAndTax' = '2NightsRoomAndTax',
  '10PercentCostOfStay' = '10PercentCostOfStay',
  '20PercentCostOfStay' = '20PercentCostOfStay',
  '30PercentCostOfStay' = '30PercentCostOfStay',
  '40PercentCostOfStay' = '40PercentCostOfStay',
  '50PercentCostOfStay' = '50PercentCostOfStay',
  '60PercentCostOfStay' = '60PercentCostOfStay',
  '70PercentCostOfStay' = '70PercentCostOfStay',
  '80PercentCostOfStay' = '80PercentCostOfStay',
  '90PercentCostOfStay' = '90PercentCostOfStay',
  FullCostOfStay = 'FullCostOfStay',
}
